onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Cyc {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Stb {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.We {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Adr {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Sel {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Stall {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Ack {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Err {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Rty {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Cyc {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Stb {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.We {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Adr {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Sel {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Stall {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Ack {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Err {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Rty {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o
add wave -noupdate -group DDR3 -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Cyc {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Stb {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.We {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Adr {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Sel {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i
add wave -noupdate -group DDR3 -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Stall {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Ack {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Err {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Rty {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Data {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tga {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgd {-radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgc {-radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o
add wave -noupdate -group DDR3 -radix hexadecimal -radixshowbase 1 /testrunner/__ts/sim_ut/de10nano/ddr3/bus_data_i
add wave -noupdate -group DDR3 -radix hexadecimal -radixshowbase 1 /testrunner/__ts/sim_ut/de10nano/ddr3/bus_data_o
add wave -noupdate -height 15 -group RISCV -expand /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i
add wave -noupdate -height 15 -group RISCV -expand /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {594 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 358
configure wave -valuecolwidth 91
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {2931 ps}
