onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/clk
add wave -noupdate -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/arst
add wave -noupdate -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/rst
add wave -noupdate -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/LED
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Cyc {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Stb {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.We {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Adr {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Sel {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_i
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Stall {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Ack {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Err {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Rty {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_inst_o
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Cyc {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Stb {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.We {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Adr {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Sel {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_i
add wave -noupdate -group FLASH -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Stall {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Ack {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Err {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Rty {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/mem/bus_data_o
add wave -noupdate -group DDR3 -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Cyc {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Stb {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.We {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Adr {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Sel {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_i
add wave -noupdate -group DDR3 -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgc -radix hexadecimal}} -radixshowbase 1 -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Stall {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Ack {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Err {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Rty {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Data {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tga {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgd {-height 16 -radix hexadecimal -radixshowbase 1} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o.Tgc {-height 16 -radix hexadecimal -radixshowbase 1}} /testrunner/__ts/sim_ut/de10nano/ddr3/bus_inst_o
add wave -noupdate -group DDR3 -radix hexadecimal -radixshowbase 1 /testrunner/__ts/sim_ut/de10nano/ddr3/bus_data_i
add wave -noupdate -group DDR3 -radix hexadecimal -radixshowbase 1 /testrunner/__ts/sim_ut/de10nano/ddr3/bus_data_o
add wave -noupdate -expand -group RISCV -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Stall -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Ack -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Err -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Rty -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tgc -radix hexadecimal}} -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Stall {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Ack {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Err {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Rty {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Data {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tga {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tgd {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i.Tgc {-height 13 -radix hexadecimal}} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_i
add wave -noupdate -expand -group RISCV -radix hexadecimal -childformat {{/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Cyc -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Stb -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.We -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Adr -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Sel -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Data -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tga -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tgd -radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tgc -radix hexadecimal}} -expand -subitemconfig {/testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Cyc {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Stb {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.We {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Adr {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Sel {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Data {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tga {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tgd {-height 13 -radix hexadecimal} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o.Tgc {-height 13 -radix hexadecimal}} /testrunner/__ts/sim_ut/de10nano/riscv/bus_inst_o
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_vld
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_freeze
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_retired
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_PC
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_PC_next
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_br
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_br_miss
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_br_pred_PC_next
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_br_taken
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_inst
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rs1
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rs1_data
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rs2
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rs2_data
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rd
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rd_wr
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_rd_data
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_mem_access
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_mem_rdata
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_order
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_order_next
add wave -noupdate -expand -group RISCV -expand -group EXU -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/exu/exu_trap
add wave -noupdate -expand -group RVFI /testrunner/__ts/sim_ut/de10nano/riscv/exu/alu_vld
add wave -noupdate -expand -group RVFI /testrunner/__ts/sim_ut/de10nano/riscv/exu/bru_vld
add wave -noupdate -expand -group RVFI /testrunner/__ts/sim_ut/de10nano/riscv/exu/csu_vld
add wave -noupdate -expand -group RVFI /testrunner/__ts/sim_ut/de10nano/riscv/exu/lsu_vld
add wave -noupdate -expand -group RVFI /testrunner/__ts/sim_ut/de10nano/riscv/exu/mpu_vld
add wave -noupdate -expand -group RVFI -radix hexadecimal -childformat {{{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[5]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[4]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[3]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[2]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[1]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[0]} -radix hexadecimal}} -expand -subitemconfig {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[5]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[4]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[3]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[2]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[1]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid[0]} {-radix hexadecimal}} /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_valid
add wave -noupdate -expand -group RVFI -radix decimal -childformat {{{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[5]} -radix decimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[4]} -radix decimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[3]} -radix decimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[2]} -radix decimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[1]} -radix decimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[0]} -radix decimal}} -expand -subitemconfig {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[5]} {-radix decimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[4]} {-radix decimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[3]} {-radix decimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[2]} {-radix decimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[1]} {-radix decimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order[0]} {-radix decimal}} /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_order
add wave -noupdate -expand -group RVFI -radix hexadecimal -childformat {{{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[5]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[4]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[3]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[2]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[1]} -radix hexadecimal} {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[0]} -radix hexadecimal}} -expand -subitemconfig {{/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[5]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[4]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[3]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[2]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[1]} {-radix hexadecimal} {/testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn[0]} {-radix hexadecimal}} /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_insn
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_trap
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_halt
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_intr
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mode
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_ixl
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rs1_addr
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rs1_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rs2_addr
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rs2_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rd_addr
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_rd_wdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_pc_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_pc_wdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mem_addr
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mem_rmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mem_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mem_wmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_mem_wdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_mcycle_rmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_mcycle_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_mcycle_wmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_mcycle_wdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_minstret_rmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_minstret_rdata
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_minstret_wmask
add wave -noupdate -expand -group RVFI -radix hexadecimal /testrunner/__ts/sim_ut/de10nano/riscv/rvfi_csr_minstret_wdata
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3040 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 253
configure wave -valuecolwidth 91
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1680 ps} {3922 ps}
